package com;

import com.tOrderItem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tOrder extends tOrderItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public tOrder() {
	}

}